# Generated by Django 5.0.14 on 2026-06-14 03:05

import django.db.models.deletion
import django.utils.timezone
import tracktrace.traceapi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('ocean', 'Ocean'), ('air', 'Air')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('gate-in', 'Gate in at origin'), ('loaded', 'Loaded on board'), ('departed', 'Departed origin'), ('in-transit', 'In transit'), ('transshipment', 'Transshipment'), ('arrived', 'Arrived at destination'), ('discharged', 'Discharged'), ('available', 'Available for pickup'), ('out-for-delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('delayed', 'Delayed')], db_index=True, default='booked', max_length=20)),
                ('carrier_name', models.CharField(max_length=100)),
                ('carrier_code', models.CharField(blank=True, db_index=True, max_length=10)),
                ('bill_of_lading', models.CharField(blank=True, db_index=True, max_length=40)),
                ('booking_number', models.CharField(blank=True, db_index=True, max_length=40)),
                ('awb_number', models.CharField(blank=True, db_index=True, max_length=20, validators=[tracktrace.traceapi.validators.validate_awb_number])),
                ('shipper_name', models.CharField(max_length=150)),
                ('shipper_address', models.CharField(blank=True, max_length=255)),
                ('consignee_name', models.CharField(max_length=150)),
                ('consignee_address', models.CharField(blank=True, max_length=255)),
                ('origin_port', models.CharField(max_length=100)),
                ('origin_code', models.CharField(blank=True, max_length=10)),
                ('origin_country', models.CharField(blank=True, max_length=60)),
                ('destination_port', models.CharField(max_length=100)),
                ('destination_code', models.CharField(blank=True, max_length=10)),
                ('destination_country', models.CharField(blank=True, max_length=60)),
                ('destination_city', models.CharField(blank=True, max_length=80)),
                ('vessel_name', models.CharField(blank=True, max_length=100)),
                ('voyage_number', models.CharField(blank=True, max_length=20)),
                ('flight_number', models.CharField(blank=True, max_length=20)),
                ('etd', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('weather', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.weather')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(db_index=True, max_length=11, validators=[tracktrace.traceapi.validators.validate_container_number])),
                ('container_type', models.CharField(blank=True, max_length=10)),
                ('seal_number', models.CharField(blank=True, max_length=30)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='traceapi.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='CargoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('hs_code', models.CharField(blank=True, max_length=12)),
                ('pieces', models.PositiveIntegerField(default=1)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='traceapi.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('location_code', models.CharField(blank=True, max_length=10)),
                ('vessel_or_flight', models.CharField(blank=True, max_length=100)),
                ('event_datetime', models.DateTimeField(db_index=True)),
                ('is_estimated', models.BooleanField(default=False)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='traceapi.container')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='traceapi.shipment')),
            ],
            options={
                'ordering': ['event_datetime'],
            },
        ),
    ]
