# Generated by Django 5.0.14 on 2026-06-14 03:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=80)),
                ('temperature', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'unique_together': {('city', 'country')},
            },
        ),
    ]
